// REACT/src/components/list/TodoListComponent.js
import React, { useEffect, useState } from 'react';
import { objectToGETparams } from '../function';
import { POST } from '../function/methods';
import useFetch from '../hook/useFetch';
import Loader from '../Loader';
import SelectInput from '../SelectInput';
import TodoListLine from './item/TodoListLine';

const TodoListComponent = ({ init = false }) => {
	const [result, load, loading] = useFetch();
	const [resultSend, loadSend, loadingSend] = useFetch();
	const [newTodo, setNewTodo] = useState({ value: '', category: null });
	const [todoLists, setTodoLists] = useState([]);
	const [categories, setCategories] = useState([]);
	const [filter, setFilter] = useState({});

	useEffect(() => {
		handleLoad();
	}, [filter]);

	useEffect(() => {
		if (result && result.success) {
			setTodoLists(result.todoLists);
			setCategories(result.categories);
		}
	}, [result]);

	useEffect(() => {
		if (resultSend && resultSend.success) {
			handleAdd(resultSend.todoList);
		}
	}, [resultSend]);

	const handleLoad = () => {
		load({
			url: 'todolist' + objectToGETparams(filter),
		});
	};

	const handleAdd = newTodoGiven => {
		const todoTemp = todoLists.slice();
		todoTemp.unshift(newTodoGiven);
		setTodoLists(todoTemp);

		setNewTodo({ value: '', category: null });
	};

	const handleDelete = index => {
		const todoTemp = todoLists.slice();
		todoTemp.splice(index, 1);
		setTodoLists(todoTemp);
	};

	const handleSubmit = e => {
		e.preventDefault();
		loadSend({
			url: 'todolist',
			method: POST,
			body: newTodo,
		});
	};

	const setValue = ({ target }) => {
		setNewTodo({ ...newTodo, value: target.value });
	};

	const setSelect = ({ id, name }) => {
		if (id) {
			setFilter({ category: id });
		}
		if (!name) {
			setFilter({});
		}
	};

	const setCategory = category => {
		setNewTodo({ ...newTodo, category });
	};

	return (
		<div className="container todolist">
			<div className="row justify-content-center">
				<div className="col-md-12">
					<div className="card">
						<div className="card-header">
							<div>Todo List</div>
							<div>
								<SelectInput
									data={categories}
									attribute="name"
									handleCallback={setSelect}
								/>
							</div>
						</div>
						<div className="card-body">
							{loading ? (
								<div>
									<Loader />
								</div>
							) : (
								<table className="table">
									<thead>
										<tr>
											<th scope="col" className="text-center">
												Todo
											</th>
											<th scope="col" className="text-center">
												Category
											</th>
											<th scope="col" className="text-center">
												Actions
											</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>
												<input
													onChange={setValue}
													value={newTodo.value}
													type="text"
													name="message"
													className="form-control"
												/>
											</td>
											<td>
												<SelectInput
													data={categories}
													attribute="name"
													handleCallback={setCategory}
													default-value={newTodo.category ? newTodo.category.name : ''}
												/>
											</td>
											<td className="text-end">
												<input
													className="btn btn-primary col-auto"
													onClick={/*prevent*/ handleSubmit}
													type="submit"
													value="Ajouter"
												/>
											</td>
										</tr>
										{todoLists.map((todolist, index) => (
											<TodoListLine
												key={todolist.id}
												todoListGiven={todolist}
												index={index}
												handleDeleteCallBack={handleDelete}
												categories={categories}
											/>
										))}
									</tbody>
								</table>
							)}
						</div>
					</div>
				</div>
			</div>
		</div>
	);
};

export default TodoListComponent;

// API/resources/js/components/TodoListComponent.vue


<script setup>
import { ref, watch, onMounted, reactive, computed } from "@vue/runtime-core";
import { DELETE, POST } from "../methods.js";
import useCounter from "../useCounter.js";
import useFetch from "../useFetch.js";
import useState from "../useState.js";
import { objectToGETparams } from "../index.js";
import TodoListLine from "./TodoListLineComponent.vue";
import SelectInput from "./SelectInputComponent.vue";
import Loader from "./LoaderComponent.vue";

const [result, load, loading] = useFetch();
const [resultSend, loadSend, loadingSend] = useFetch();
const defaultValue = { value: "", category: null };
const [newTodo, setNewTodo] = useState(defaultValue);
const todoLists = ref([]);
const categories = ref([]);
const filter = ref({});

const handleLoad = () => {
  load({
    url: "todolist" + objectToGETparams(filter.value),
  });
};

const handleAdd = (newTodoGiven) => {
  const todoTemp = todoLists.value.slice();
  todoTemp.unshift(newTodoGiven);
  todoLists.value = todoTemp;
  setNewTodo(defaultValue);
};

const handleDelete = (index) => {
  todoLists.value.splice(index, 1);
};

const handleSubmit = (e) => {
  e.preventDefault();
  loadSend({
    url: "todolist",
    method: POST,
    body: newTodo(),
  });
};

const setValue = ({ target }) => {
  setNewTodo({ ...newTodo(), value: target.value });
};

const setSelect = ({ id, name }) => {
  if (id) {
    filter.value = { category: id };
  }
  if (!name) {
    filter.value = {};
  }
};

const setCategory = (category) => {
  setNewTodo({ ...newTodo(), category });
};

watch(filter, (currentValue, oldValue) => {
  handleLoad();
});

watch(result, (currentValue, oldValue) => {
  if (currentValue && currentValue.success) {
    todoLists.value = currentValue.todoLists;
    categories.value = currentValue.categories;
  }
});

watch(resultSend, (currentValue, oldValue) => {
  if (currentValue && currentValue.success) {
    handleAdd(currentValue.todoList);
  }
});

onMounted(() => {
  handleLoad();
});
</script>

<template>
  <div class="container todolist">
    <div class="row justify-content-center">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <div>Todo List</div>
            <div>
              <SelectInput
                :data="categories"
                :attribute="'name'"
                :handle-callback="setSelect"
              />
            </div>
          </div>
          <div class="card-body">
            <div v-if="loading">
              <Loader />
            </div>
            <table class="table" v-else>
              <thead>
                <tr>
                  <th scope="col" class="text-center">Todo</th>
                  <th scope="col" class="text-center">Category</th>
                  <th scope="col" class="text-center">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    <input
                      @input="setValue"
                      :value="newTodo().value"
                      type="text"
                      name="message"
                      class="form-control"
                    />
                  </td>
                  <td>
                    <SelectInput
                      :data="categories"
                      :attribute="'name'"
                      :handle-callback="setCategory"
                      :default-value="
                        newTodo().category ? newTodo().category.name : ''
                      "
                    />
                  </td>
                  <td class="text-end">
                    <input
                      class="btn btn-primary col-auto"
                      v-on:click.prevent="handleSubmit"
                      type="submit"
                      value="Ajouter"
                    />
                  </td>
                </tr>
                <TodoListLine
                  v-for="(todolist, index) in todoLists"
                  :key="todolist.id"
                  :todo-list="todolist"
                  :index="index"
                  :handle-delete-call-back="handleDelete"
                  :categories="categories"
                >
                </TodoListLine>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
